### ISSUE TITLE
Generate Profile

### ISSUE THREAD

**Issue by elrodrigues** [cs130-w21/20#1]
## Epic
We want the user to generate and view their profile from their stock portfolio.

## User Stories
- [x] Upload/Select Stock Portfolio #3
- [x] Generate Profile #4 
- [x] Present Profile #5 
- [x] View Profile on Mobile Devices #6 
- [x] Generate Profile/Session ID (opt) #7 
- [x] Add compare endpoints #30
