### ISSUE TITLE
Present Compatibility

### ISSUE THREAD

**Issue by elrodrigues** [cs130-w21/20#10]
## User Story
As a **User**, I would like **my compatibility with another User presented clearly** so that **I can interpret it**.

## Detailed Description
The application will present the user's compatibility for easy reading.

## Tasks
- [x] Comparison page #37 
- [x] (Opt) Flesh out UI #39 

## Acceptance Criteria
- [x] Given **User's IDs**, then **the page displays our compatibility**
- [x] Given **User's IDs**, then **the results are easy to interpret with explanations**
- [x] Given **Tablet or Mobile devices**, then **the comparison results are presented with nothing functionally broken**

**Comment by elrodrigues** [comment]
Closing: all present tasks completed
