### ISSUE TITLE
Upload/Select Portfolio

### ISSUE THREAD

**Issue by elrodrigues** [cs130-w21/20#3]
## User Story
As a **User**, I would like **upload/select my portfolio** so that **I can generate my profile**.

## Detailed Description
The User should be able to upload their portfolio or choose their portfolio from a list of tickers.

## Tasks
- [x] Let user input tickers for one stock (UI) (1/2) #14 
- [x] Validate user tickers (API) #15 
- [x] Add database to `flaskr` #16 
- [x] Let user add multiple stocks and display them as a list (UI) (2/2) #17 

## Acceptance Criteria (TBD)
- [x] Given **webpage**, then **User can enter their tickers and numbers held of each**
- [x] Given **User's tickers**, then **application can query API and validate input**
- [x] Given **User's validated input**, then **application will store its work in a database**
