### ISSUE TITLE
Add compare endpoints: UI+Flask Server

### ISSUE THREAD

**Issue by elrodrigues** [cs130-w21/20#30]
## User Story
As a **User**, I would like **view the Compare page** so that **I can enter my IDs to compare**.

## Detailed Description
Add "compare" endpoints in Flask app and a basic "compare" webpage in preparation for Sprint 3.

## Tasks
- [x] Add "compare" endpoint/route in Flask server #31 
- [x] Add basic "compare" page with inputs #32 

## Acceptance Criteria
- [x] Given **My Profile**, then **I can navigate to, view, and interact with the Compare page of the Application**

**Comment by elrodrigues** [comment]
Closing: compare page and endpoint added.
