### ISSUE TITLE
Create Profile

### ISSUE THREAD

**Issue by elrodrigues** [cs130-w21/20#4]
## User Story
As a **User**, I would like **the app to create my profile** so that **I know my profile from my portfolio**.

## Detailed Description
The application will generate the user's personality profile from their portfolio.

## Tasks
- [x] Generate random non-assigned session ID #21
- [x] Create portfolio to personality profile algorithm #22
- [x] Store session ID and profile in database #23
- [x] Algorithm Inputs and Outputs #24 

## Acceptance Criteria
- [x] Given **Portfolio**, then **Application creates and stores my personality profile**
- [x] Given **Portfolio**, then **I receive a random ID I can share with another User**

**Comment by elrodrigues** [comment]
Closing: all tasks completed
