### ISSUE TITLE
Add documentation for Epic 1 and 2

### ISSUE THREAD

**Issue by elrodrigues** [cs130-w21/20#51]
## User Story
As a **User**, I would like **see some documentation** so that **I can better understand the application**.

## Task
- [x] Add API documentation #40 
- [x] Add User Manual #41 

## Acceptance Criteria
- [x] Given **User Manual**, then **I can setup the application with no hassle**
- [x] Given **API Documentation**, then **I can understand the application's design**

**Comment by elrodrigues** [comment]
Closed: added user manual and API documentation
